package app.securevault.core.crypto

/**
 * Fixed Argon2id vectors, shared by every platform's backend test.
 *
 * ## Why these are not the RFC 9106 vectors
 *
 * RFC 9106 section 5.3 gives one Argon2id vector, and it uses a secret key and associated data.
 * `argon2kt`, the Android implementation, exposes neither, so that vector cannot be run through
 * [Argon2Backend] at all. A parameter one platform cannot supply is a parameter that cannot be
 * shared, which is why the interface has no secret or AD arguments. The RFC vector is recorded
 * below for reference, not for execution.
 *
 * ```
 * RFC 9106 §5.3 (reference only, NOT runnable through Argon2Backend)
 *   password  32 bytes of 0x01      secret   8 bytes of 0x03
 *   salt      16 bytes of 0x02      assoc.  12 bytes of 0x04
 *   p=4  m=32 KiB  t=3  outLen=32  v=0x13
 *   tag: 0d640df58d78766c08c037a34a8b53c9d01ef0452d75b65eb52520e96b01e659
 * ```
 *
 * ## The expected values below are NOT filled in, on purpose
 *
 * Every entry has `expectedHex = ""`. I do not have a trustworthy source for Argon2id outputs
 * without a secret and associated data, and inventing them -- or generating them from one of the
 * two implementations we are trying to compare -- would produce a test that proves nothing while
 * looking like it proves everything. A vector generated by the implementation under test is a
 * tautology, not a vector.
 *
 * Fill them from the **reference implementation**, which packages on Ubuntu:
 *
 * ```
 * sudo apt install argon2
 * # -id = Argon2id, -v 13 = version 0x13, -t iterations, -m log2(memory KiB), -p lanes, -l outLen
 * echo -n "securevault-vector-1" | argon2 securevault-salt-16b -id -v 13 -t 3 -m 15 -p 1 -l 32 -r
 * ```
 *
 * `-m` is the base-2 logarithm of the memory cost, so `-m 15` is 32768 KiB. `-r` prints the raw
 * hash as hex with nothing else. The salt is passed literally and must be at least 8 bytes.
 *
 * Until these are populated and executed on both platforms, cross-platform vault compatibility is
 * **designed and reasoned about, not demonstrated**, and must be described that way.
 */
object Argon2Vectors {

    data class Vector(
        val label: String,
        val password: String,
        val salt: String,
        val memoryKib: Int,
        val iterations: Int,
        val parallelism: Int,
        val outputBytes: Int,
        /** Lower-case hex. Empty means "not yet taken from the reference implementation". */
        val expectedHex: String
    ) {
        val isPopulated: Boolean get() = expectedHex.isNotBlank()

        /** The exact command that produces [expectedHex]. Printed when a vector is skipped. */
        val referenceCommand: String
            get() = "echo -n \"$password\" | argon2 $salt -id -v 13 -t $iterations " +
                "-m ${log2(memoryKib)} -p $parallelism -l $outputBytes -r"

        private fun log2(value: Int): Int {
            var v = value
            var n = 0
            while (v > 1) { v = v shr 1; n++ }
            return n
        }
    }

    /**
     * Parameters chosen to cover what SecureVault actually produces: the calibration floor, the
     * default, a high-memory device, and a multi-lane case. Memory values are powers of two so the
     * reference CLI's log2 argument is exact.
     */
    val ALL = listOf(
        Vector(
            label = "floor: 16 MiB, t=3, p=1",
            password = "securevault-vector-1", salt = "securevault-salt-16b",
            memoryKib = 16_384, iterations = 3, parallelism = 1, outputBytes = 32,
            expectedHex = ""
        ),
        Vector(
            label = "default: 64 MiB, t=3, p=2",
            password = "correct horse battery staple", salt = "securevault-salt-16b",
            memoryKib = 65_536, iterations = 3, parallelism = 2, outputBytes = 32,
            expectedHex = ""
        ),
        Vector(
            label = "high memory: 256 MiB, t=3, p=4",
            password = "a longer master passphrase with spaces", salt = "0123456789abcdef",
            memoryKib = 262_144, iterations = 3, parallelism = 4, outputBytes = 32,
            expectedHex = ""
        ),
        Vector(
            label = "unicode password, 32 MiB, t=4, p=1",
            password = "p\u00e4ssw\u00f6rd-\u00fcml\u00e4ut", salt = "securevault-salt-16b",
            memoryKib = 32_768, iterations = 4, parallelism = 1, outputBytes = 32,
            expectedHex = ""
        )
    )

    val populated: List<Vector> get() = ALL.filter { it.isPopulated }
}
